language: python
python:
        - '3.6'

before_script:
        - pip install -r requirements.txt

branches:
     only:
        - staging

env: DJANGO_SETTINGS_MODULE="weather_cam.settings.travis"

services:
        - postgresql

script:
        - python manage.py test
