language: python
python:
        - '3.6'

before_script:
        - pip install -r requirements.txt

branches:
     only:
        - staging

services:
        - postgresql

script:
        - python manage.py test
